### PR TITLE
Electrochemistry  has its own namespace

### PR DESCRIPTION
**Pull request by francescalb**
I have one question: now I need the whole namespace of electrochemistry when writing relations to entities in electrochemistry from battinfo. Is this correct?

### CODE REVIEW

**Comment by jesper-friis** [comment]
It is possible to define "elchem" as a namespace prefix for http://emmo.info/electrochemistry. Then you can prefix all references in battinfo to electrochemistry with "elchem:"

**Comment by francescalb** [comment]
> It is possible to define "elchem" as a namespace prefix for http://emmo.info/electrochemistry. Then you can prefix all references in battinfo to electrochemistry with "elchem:"

It works with just using electrochemistry, it seems.

**Comment by francescalb** [comment]
> > It is possible to define "elchem" as a namespace prefix for http://emmo.info/electrochemistry. Then you can prefix all references in battinfo to electrochemistry with "elchem:"
> 
> It works with just using electrochemistry, it seems.

Correction to myself: It worked in protege, but not in emmopython with emmochecks

**Comment by francescalb** [comment]
> It is possible to define "elchem" as a namespace prefix for http://emmo.info/electrochemistry. Then you can prefix all references in battinfo to electrochemistry with "elchem:"

I used electrochemistry and updated the exceptions list so should be fine now. Let me know if something else should be changed (I sued electrochemistry instead of elchem for short name)

**Review by jesper-friis — APPROVED** [review]
Looks very good. I agree that using electrochemistry as prefix is better than just elchem.

**Pull request merged**
