### PR TITLE
Fix branches that trigger GH Pages build

### LINKED ISSUE #50: Continuous deployment to github pages has stopped working

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #50.

I've moved the version regexes to `tags`, meaning if a versioned tag is created this workflow will also run - note this is also true if the tag is created for a commit in a PR.

### CODE REVIEW

**Comment by CasperWA** [comment]
Note, I haven't tested this.

**Comment by francescalb** [comment]
Is this pull request still valid?

**Comment by CasperWA** [comment]
> Is this pull request still valid?

Yes - it's just waiting for a review, essentially.

What it does: Change the "Update GitHub Pages" workflow to run whenever a push is performed to the `master` branch and when tags are pushed with versioning style. Finally, the workflow only runs if we're in the BIG-MAP/BattINFO repository (i.e., not in a fork).
Concerning the tags, my original comment still holds as well: if someone creates a new version tag and pushes it to a branch on this repository it will trigger this workflow - whether in a PR or not. Perhaps this is not desired? Instead it might be desired to run it when publishing a GitHub release?

**Review by francescalb — APPROVED** [review]
Ok, seems good to me. It had been waiting for quite some time, so wanted to check i out.

**Comment by CasperWA** [comment]
> Ok, seems good to me. It had been waiting for quite some time, so wanted to check i out.

Do you have opinions about the questions I've posed in my latest comment?

**Comment by francescalb** [comment]
> > Ok, seems good to me. It had been waiting for quite some time, so wanted to check i out.
> 
> Do you have opinions about the questions I've posed in my latest comment?

I guess we would always want to update githubpages if there is an update on tags, and so it makes sense to run this workflow when it is updated in a branch to check that everything works fine before pushing to master, no?

**Pull request merged**
